// Central product data store — used across all pages
import { Product } from '@/types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Structured Charcoal Blazer',
    description: 'A sharp, contemporary blazer crafted from premium wool-blend fabric. Slim-fit silhouette with double-button closure, notch lapels, and welt pockets. Ideal for boardroom meetings or evening events.',
    brand: 'Zara',
    category: 'blazers',
    subcategory: 'formal',
    sku: 'ZAR-BLZ-001',
    price: 5999,
    offerPrice: 3499,
    discountPercent: 42,
    stock: 45,
    sizes: [{ size: 'S', stock: 10 }, { size: 'M', stock: 15 }, { size: 'L', stock: 12 }, { size: 'XL', stock: 8 }],
    colors: [{ name: 'Charcoal', hex: '#374151' }, { name: 'Navy', hex: '#1e3a5f' }],
    material: '65% Wool, 35% Polyester',
    gender: 'men',
    season: 'winter',
    tags: ['blazer', 'formal', 'men', 'office', 'zara'],
    images: ['/prod-blazer.png', '/prod-blazer.png', '/prod-blazer.png'],
    thumbnail: '/prod-blazer.png',
    rating: 4.8,
    reviewCount: 124,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    isLimitedEdition: false,
    isActive: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: '2',
    name: 'Floral Wrap Midi Dress',
    description: 'An effortlessly elegant wrap dress featuring a flowing midi silhouette with delicate floral print. Made from lightweight viscose fabric that drapes beautifully. Features a V-neck, adjustable wrap front, and flutter sleeves.',
    brand: 'Mango',
    category: 'dresses',
    subcategory: 'casual',
    sku: 'MNG-DRS-002',
    price: 3999,
    offerPrice: 2199,
    discountPercent: 45,
    stock: 30,
    sizes: [{ size: 'XS', stock: 5 }, { size: 'S', stock: 10 }, { size: 'M', stock: 10 }, { size: 'L', stock: 5 }],
    colors: [{ name: 'Cream Floral', hex: '#F5F0E8' }, { name: 'Sage', hex: '#87A96B' }],
    material: '100% Viscose',
    gender: 'women',
    season: 'summer',
    tags: ['dress', 'floral', 'women', 'casual', 'mango'],
    images: ['/prod-dress.png', '/prod-dress.png', '/prod-dress.png'],
    thumbnail: '/prod-dress.png',
    rating: 4.9,
    reviewCount: 87,
    isFeatured: true,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: true,
    isLimitedEdition: false,
    isActive: true,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: '3',
    name: 'Classic White Sneakers',
    description: 'Iconic clean minimalist sneakers with a vulcanised rubber sole. Premium leather upper with perforated toe box. Cushioned insole for all-day comfort. Goes with everything.',
    brand: 'Nike',
    category: 'footwear',
    subcategory: 'sneakers',
    sku: 'NKE-SNK-003',
    price: 5999,
    offerPrice: 4299,
    discountPercent: 28,
    stock: 60,
    sizes: [{ size: '6', stock: 5 }, { size: '7', stock: 10 }, { size: '8', stock: 15 }, { size: '9', stock: 15 }, { size: '10', stock: 10 }, { size: '11', stock: 5 }],
    colors: [{ name: 'White', hex: '#FFFFFF' }, { name: 'Off White', hex: '#F5F0E8' }],
    material: 'Premium Leather Upper, Rubber Sole',
    gender: 'unisex',
    season: 'all-season',
    tags: ['sneakers', 'footwear', 'casual', 'nike', 'white'],
    images: ['/prod-sneakers.png', '/prod-sneakers.png', '/prod-sneakers.png'],
    thumbnail: '/prod-sneakers.png',
    rating: 4.7,
    reviewCount: 210,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    isLimitedEdition: false,
    isActive: true,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: '4',
    name: 'Linen Kurta Set',
    description: 'Handcrafted linen kurta set with subtle hand-block embroidery at neckline and hem. Comes with matching straight pants. Breathable and perfect for summer occasions, festive gatherings, or casual wear.',
    brand: 'Fabindia',
    category: 'ethnic',
    subcategory: 'kurta-sets',
    sku: 'FAB-KRT-004',
    price: 2999,
    offerPrice: 1799,
    discountPercent: 40,
    stock: 25,
    sizes: [{ size: 'S', stock: 5 }, { size: 'M', stock: 8 }, { size: 'L', stock: 8 }, { size: 'XL', stock: 4 }],
    colors: [{ name: 'Ivory', hex: '#FFFFF0' }, { name: 'Mint', hex: '#98FF98' }],
    material: '100% Linen',
    gender: 'men',
    season: 'summer',
    tags: ['kurta', 'ethnic', 'men', 'linen', 'fabindia'],
    images: ['/prod-kurta.png', '/prod-kurta.png', '/prod-kurta.png'],
    thumbnail: '/prod-kurta.png',
    rating: 4.6,
    reviewCount: 56,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    isLimitedEdition: false,
    isActive: true,
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: '5',
    name: 'Oversized Graphic Hoodie',
    description: 'A heavyweight cotton-blend hoodie with a bold graphic print. Features a kangaroo pocket, adjustable drawstring hood, and ribbed cuffs. The ultimate streetwear essential.',
    brand: 'Adidas',
    category: 'hoodies',
    subcategory: 'casual',
    sku: 'ADI-HDY-005',
    price: 3499,
    offerPrice: 2499,
    discountPercent: 29,
    stock: 50,
    sizes: [{ size: 'S', stock: 10 }, { size: 'M', stock: 15 }, { size: 'L', stock: 15 }, { size: 'XL', stock: 10 }],
    colors: [{ name: 'Cream', hex: '#FFFDD0' }, { name: 'Black', hex: '#000000' }, { name: 'Sage', hex: '#87A96B' }],
    material: '80% Cotton, 20% Polyester',
    gender: 'unisex',
    season: 'winter',
    tags: ['hoodie', 'casual', 'streetwear', 'adidas', 'graphic'],
    images: ['/cat-men.png', '/cat-men.png'],
    thumbnail: '/cat-men.png',
    rating: 4.5,
    reviewCount: 189,
    isFeatured: true,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: true,
    isLimitedEdition: false,
    isActive: true,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: '6',
    name: 'Premium Silk Saree',
    description: 'A luxurious pure silk saree with zari border and intricate woven motifs. Comes with an unstitched blouse piece. Perfect for weddings and festive occasions.',
    brand: 'Fabindia',
    category: 'sarees',
    subcategory: 'ethnic',
    sku: 'FAB-SAR-006',
    price: 8999,
    offerPrice: 6499,
    discountPercent: 28,
    stock: 15,
    sizes: [{ size: 'Free Size', stock: 15 }],
    colors: [{ name: 'Royal Blue', hex: '#4169E1' }, { name: 'Deep Red', hex: '#8B0000' }],
    material: 'Pure Silk',
    gender: 'women',
    season: 'all-season',
    tags: ['saree', 'ethnic', 'women', 'silk', 'wedding'],
    images: ['/cat-women.png', '/cat-women.png'],
    thumbnail: '/cat-women.png',
    rating: 4.9,
    reviewCount: 43,
    isFeatured: true,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    isLimitedEdition: true,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: '7',
    name: 'Kids Denim Dungaree Set',
    description: 'Adorable and durable denim dungaree set for active kids. Features adjustable straps, front bib pocket, and side pockets. Comes with a striped cotton tee.',
    brand: 'H&M',
    category: 'kids',
    subcategory: 'boys',
    sku: 'HM-KDS-007',
    price: 1499,
    offerPrice: 999,
    discountPercent: 33,
    stock: 40,
    sizes: [{ size: '2Y', stock: 8 }, { size: '4Y', stock: 10 }, { size: '6Y', stock: 12 }, { size: '8Y', stock: 10 }],
    colors: [{ name: 'Blue', hex: '#4169E1' }, { name: 'Black', hex: '#000000' }],
    material: '98% Cotton, 2% Elastane',
    gender: 'kids',
    season: 'all-season',
    tags: ['kids', 'denim', 'dungaree', 'boys', 'hm'],
    images: ['/cat-kids.png', '/cat-kids.png'],
    thumbnail: '/cat-kids.png',
    rating: 4.7,
    reviewCount: 78,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    isLimitedEdition: false,
    isActive: true,
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: '8',
    name: 'Slim Fit Chino Trousers',
    description: 'Versatile slim-fit chinos in stretch cotton fabric. Features a mid-rise waistband, front welt pockets, and button closure. Available in multiple colours — pair with anything.',
    brand: 'Tommy Hilfiger',
    category: 'trousers',
    subcategory: 'casual',
    sku: 'TH-TRS-008',
    price: 3999,
    offerPrice: 2799,
    discountPercent: 30,
    stock: 35,
    sizes: [{ size: '28', stock: 5 }, { size: '30', stock: 10 }, { size: '32', stock: 10 }, { size: '34', stock: 7 }, { size: '36', stock: 3 }],
    colors: [{ name: 'Khaki', hex: '#C3B091' }, { name: 'Navy', hex: '#1e3a5f' }, { name: 'Olive', hex: '#6B7C5A' }],
    material: '97% Cotton, 3% Elastane',
    gender: 'men',
    season: 'all-season',
    tags: ['chinos', 'trousers', 'men', 'casual', 'tommy'],
    images: ['/prod-kurta.png', '/prod-kurta.png'],
    thumbnail: '/prod-kurta.png',
    rating: 4.6,
    reviewCount: 95,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: false,
    isLimitedEdition: false,
    isActive: true,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-06-01'),
  },
];

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find(p => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return PRODUCTS.filter(p => p.category === category || p.gender === category);
}

export function getProductsByFilter(filter: string): Product[] {
  switch (filter) {
    case 'new': return PRODUCTS.filter(p => p.isNewArrival);
    case 'sale': return PRODUCTS.filter(p => p.offerPrice && p.offerPrice < p.price);
    case 'trending': return PRODUCTS.filter(p => p.isTrending);
    case 'featured': return PRODUCTS.filter(p => p.isFeatured);
    default: return PRODUCTS;
  }
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return PRODUCTS.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.brand.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q) ||
    p.tags.some(t => t.includes(q))
  );
}
